module.exports = {
  SOLICITANTE: "$SOLICITANTE",
  LOGIN_CONVOCADO: "$LOGIN_CONVOCADO",
  NOME_CONVOCADO: "$NOME_CONVOCADO",
  DATA: "$DATA",
  HORA_INICIAL: "$HORA_INICIAL",
  HORA_FINAL: "$HORA_FINAL",
  LOCAL: "$LOCAL",
  SALA: "$SALA",
  ASSUNTO: "$ASSUNTO",
  PAUTA: "$PAUTA",
  EMAIL_CONVOCADO: "$EMAIL_CONVOCADO",
  SITUACAO: "$SITUACAO"
};
